MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BE

resources/views/layouts/app.blade.php

correccion de estilo en app_layaut

---

app/Http/Controllers/RetirementFundController.php

correcion en la consulta de modalidades para archivo fondo retiro

---

app/Http/Controllers/AffiliateController.php
resources/assets/js/components/affiliate/Police.vue
resources/assets/js/components/affiliate/ShowAffiliate.vue
resources/views/affiliates/show.blade.php

El cehuz se comio a la karem dicen

completado al 50% edicion del afiliado

---

app/Http/Controllers/RetirementFundController.php
package-lock.json
resources/assets/js/components/affiliate/Police.vue
resources/assets/js/components/ret_fun/Info.vue
resources/views/affiliates/affiliate_personal_information.blade.php
resources/views/affiliates/show.blade.php
resources/views/ret_fun/info.blade.php
resources/views/ret_fun/show.blade.php
routes/web.php

edicion de tramite info fondo de retiro

---

resources/assets/js/components/ret_fun/Info.vue
resources/views/ret_fun/legal_review.blade.php

boton cancel hdp terminado XD

---

resources/views/affiliates/information_of_the_procedure.blade.php
resources/views/layouts/navigation.blade.php
routes/web.php

correcciones de bugs y boton hdp permisos

---

app/Http/Controllers/UserController.php
resources/views/users/registro.blade.php

Correccion de Creacion y actualizacion de usuarios

---

app/Http/Controllers/ContributionController.php
database/seeds/TypeContributionSeeder.php
resources/views/contribution/print/certification_availability.blade.php
resources/views/contribution/print/certification_contribution.blade.php

seeder type contribution

---

app/Http/Controllers/ContributionController.php
resources/assets/js/components/contribution/SelectContributions.vue
resources/views/contribution/select.blade.php
resources/views/ret_fun/show.blade.php
routes/breadcrumbs.php
routes/web.php

Seleccion  aportes terminada 

---

app/Models/Affiliate.php
resources/assets/js/components/contribution/SelectContributions.vue

bug fixes XD de Seleccion de Contribuciones

---

app/Helpers/Util.php
app/Models/AffiliateRecord.php
app/Observers/AffiliateObserver.php
app/Observers/RetirementFundObserver.php

estoy trabajando en la interfaz pero hasta mientras que guarde en la base los cambios que hacen los usuarios

historial del afiliado solo en base

---

app/Http/Controllers/ScannedDocumentController.php
app/Models/Affiliate.php
app/Models/ScannedDocument.php
resources/views/affiliates/create_scanned_document.blade.php
resources/views/affiliates/scanned_documents.blade.php
resources/views/affiliates/show.blade.php
routes/breadcrumbs.php
routes/web.php

store pdf v1

---

app/Console/Commands/AutomaticQualification.php
app/Console/Commands/CalculateAverage.php
app/Console/Commands/SyncLoanObservation.php
app/Exports/EcoComReports.php
app/Helpers/Util.php
app/Http/Controllers/EcoComImportExportController.php
app/Http/Controllers/EcoComReportController.php
app/Http/Controllers/LoanController.php
app/Http/Kernel.php
app/Imports/EcoComImportPagoFuturo.php
app/Models/EconomicComplement/EconomicComplement.php
resources/assets/js/app.js
resources/assets/js/components/eco_com/ImportPagoFuturo.vue
resources/assets/js/components/eco_com/ImportRents.vue
resources/assets/js/components/eco_com/Qualification.vue
resources/assets/js/components/eco_com/SelectReport.vue
resources/views/eco_com/qualification_parameters.blade.php
resources/views/eco_com/report/index.blade.php
resources/views/layouts/navigation.blade.php
resources/views/loans/index.blade.php
routes/breadcrumbs.php
routes/web.php

Set **LOAN_HOST** credentials within _.env_ file.
Setup the cronjob to synchronize every midnight like [Laravel's documentation](https://laravel.com/docs/5.8/scheduling)

Remove ecocom transactions on loan sync

---

app/Http/Controllers/EconomicComplementController.php
resources/views/eco_com/boleta.blade.php

se actualizo la ruta de liveness a eco_com para la boleta y el ci, tambien se modifico la vista para que jale base 64

mostrar fotos en el tramite

---

app/Http/Controllers/EconomicComplementController.php

ruta de las fotos

---

app/Http/Controllers/AffiliateController.php
public/css/vuetify.css
resources/assets/js/components/affiliate/ShowAffiliate.vue
resources/views/affiliates/affiliate_personal_information.blade.php
routes/web.php

Elimina registros de la tabla affiliate_devices, donde se registra los dispositivos moviles

Eliminacion de dispositovos moviles

---

app/Http/Controllers/AffiliateController.php
resources/assets/js/app.js
resources/assets/js/components/affiliate/ShowAffiliate.vue
resources/assets/js/components/eco_com/Boleta.vue
resources/views/eco_com/boleta.blade.php
resources/views/eco_com/show.blade.php
routes/web.php

Modificaciones para que la aplicacion movil interactue con el PVT-BE

Se agrego la validacion de CI, y mejoro los mensajes

---

app/Http/Controllers/EconomicComplementController.php
resources/assets/js/components/eco_com/Boleta.vue
resources/views/eco_com/boleta.blade.php
resources/views/eco_com/show.blade.php

se coloco dinamica para que aparesca los botones de validar y desvalidar CI

mejora en la visualizacion validar y desvalidad ci

---

app/Http/Controllers/EconomicComplementController.php
resources/views/eco_com/boleta.blade.php

se cambio por que dio error en los registros de tramites en recepcion

se corrigio el criterio de busqueda de findOrFail por where

---

app/Http/Controllers/AffiliateController.php
resources/views/affiliates/affiliate_personal_information.blade.php

para desvincular los celulares donde realizan el enrolamiento para el pago del beneficio economico

ocultar y mostrar el boton de desvincular movil

---

resources/views/affiliates/affiliate_personal_information.blade.php

mejora en la desvinculacion

---

app/Http/Controllers/InboxController.php

agregar usuario a la derivacion

actualizar el usuario de la derivacion multiple de recepcion

---

resources/views/affiliates/affiliate_personal_information.blade.php

se comento las linea de codigo

se comento las lineas de codigo

---

resources/views/affiliates/affiliate_personal_information.blade.php

se verifico la existencia de la variable

---

app/Models/EconomicComplement/EconomicComplement.php

para que visualice los tramites por el movil y de gestiones pasadas en el reporte todos los tramites

hace que visualice los reportes gestiones pasadas

---

resources/assets/js/components/eco_com/Boleta.vue

verifica si existe un dato en el objeto si es asi le asigna valor

validacion de variable affiliatedevice si existe datos

---

app/Exports/EcoComCompareReport.php

Discriminaba monto iguales en la prestacion de invalidez y muerte

mejora en el reporte de concurrencia

---

resources/assets/js/components/eco_com/Qualification.vue

se volvio a modificar las calificaciones

volver a formatear calificacion

---

app/Http/Controllers/EconomicComplementController.php
resources/assets/js/components/eco_com/Info.vue
resources/views/eco_com/print/paid_certificate.blade.php
routes/web.php

boleta de pago

---

app/Http/Controllers/EconomicComplementController.php
database/migrations/2021_12_24_094410_add_column_economi_complemt_tramite.php
resources/assets/js/app.js
resources/assets/js/components/eco_com/EstadoPagado.vue
resources/assets/js/components/eco_com/Info.vue
resources/assets/js/components/eco_com/SelectReport.vue
resources/views/eco_com/qualification_parameters.blade.php
routes/web.php

Cambio de estados de los tramites

Cambio de estados

---

resources/views/ret_fun/print/legal_certification.blade.php

modificacion de leyenda de la certificacion de documentos del area legar para fondo

modificacion de leyenda de la certificacion de documentos del area de legal fondo

---

app/Http/Controllers/RetirementFundCertificationController.php

cambio de la articulación de el por la en caso de devolución de aportes en el primer resuelve

---

resources/assets/js/components/ret_fun/Form.vue
resources/assets/js/components/ret_fun/Step2Applicant.vue
resources/views/ret_fun/step2_applicant.blade.php

Quitar validación de requerido fecha de desvinculación en Modalidad devolución de aportes

---

app/Http/Controllers/RetirementFundCertificationController.php
app/Models/Affiliate.php

…párrafo disponibilidad solo cuando exista clasificador

Modificaciones a resolución fondo de retiro solicitado visualización párrafo disponibilidad cuando exista clasificador con y sin aportes

---

app/Http/Controllers/EcoComImportExportController.php
app/Models/EconomicComplement/EconomicComplement.php

…o Mortuorio al momento de calcular pagos a futuro

se agrega la observación Suspendido - No tiene aportes para el Auxilio al calcular pagos a futuro

---

app/Http/Controllers/EcoComObservationController.php

…ara el auxilio desde el trámite

Se agrega restricción en la eliminación de observación de descuento para el auxilio desde el trámite

---

app/Http/Controllers/EconomicComplementController.php
routes/web.php

…l descuento del aporte  de auxilio mortuorio

Creación del  método delete_quota_aid_mortuary para la eliminación  descuento de para el auxilio mortuorio

---

app/Http/Controllers/QuotaAidCertificationController.php

Cambios a resoluciones de Cuota y auxilio mortoria en cuanto modalidad y articulo

---

app/Http/Controllers/QuotaAidCertificationController.php

corrección de certificación de jefatura nombre fondo de retiro a cuota o auxilio mortuorio

---

app/Http/Controllers/QuotaAidCertificationController.php

Modificaciones de forma en resoluciones según ticket

---

resources/views/eco_com/print/reception.blade.php

en formulario de SOLICITUD DE PAGO DEL BENEFICIO DE COMPLEMENTO ECONÓMICO

Adición de autorización para enviar notificaciones al afiliado 

---

resources/views/ret_fun/print/liquidation.blade.php

…ES Y PRESTAMO EN FORM LIQUIDACION

SE AUMENTO COLUMNA NUMERO DE PRESTAMO PARA DESCUENTOS DE TYPO  GARANTES Y PRESTAMO EN FORM LIQUIDACION
